POST https://node-videos-6e6v.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://node-videos-6e6v.onrender.com/videos

###

PUT https://node-videos-6e6v.onrender.com/videos/4fe6e6e7-72b5-42f9-bee5-3f2972137753
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o segundo video",
    "duration": 180
}

###

DELETE https://node-videos-6e6v.onrender.com/videos/4fe6e6e7-72b5-42f9-bee5-3f2972137753
